### ISSUE TITLE
Take exclude configuration via yaml

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/actions#1]
Currently the files excluded from the checks are hard coded in the shell scripts.

**Comment by umarcor** [comment]
Do you mean by an option when using the Action (which is a field in `action.yml`) or by passing a "configuration file" in YAML format to the Action?

**Comment by mithro** [comment]
Either?

**Comment by umarcor** [comment]
Then, I would suggest rewriting the scripts in Python, instead of using bash. Manipulating YAML in bash and/or detecting a "polimorfic" argument is a pain in comparison.

**Comment by mithro** [comment]
@umarcor I was hoping it could just set a list of values to an environment variable?

**Comment by umarcor** [comment]
Sure, the point is what content/syntax we allow:

```yml
uses: symbiflow/actions/checks@main
with:
  exclude: >
    a_pattern
    another_pattern
```

```yml
uses: symbiflow/actions/checks@main
with:
  exclude: |
    a_pattern
    another_pattern
```

```yml
uses: symbiflow/actions/checks@main
with:
  exclude: exclude_list.yml
```

In all cases, an envvar named `INPUT_EXCLUDE` will contain the value(s). In the first case, values are separated by spaces. In the second case, values are separated by newlines. In the last case, reading the YAML file would be required.
